services:
###> doctrine/doctrine-bundle ###
  database:
    restart: unless-stopped
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-nytodev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nytodev}
      POSTGRES_USER: ${POSTGRES_USER:-nytodev}
      TZ: ${TZ:-Europe/Paris}
      PGTZ: ${TZ:-Europe/Paris}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-nytodev}", "-U", "${POSTGRES_USER:-nytodev}"]
      timeout: 5s
      retries: 5
#      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
